#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with root privileges (sudo)."
  exit 1
fi

SERVER_IP=$(curl -s http://checkip.amazonaws.com)

if [ -z "$SERVER_IP" ]; then
  echo "Unable to retrieve the server's public IP address."
  exit 1
fi

read -p "Enter the domain name (e.g., example.com): " DOMAIN

# DNS Validation
DOMAIN_IP=$(dig +short "$DOMAIN" | tail -n 1)

if [ -z "$DOMAIN_IP" ]; then
  echo "Unable to resolve the IP address for the domain $DOMAIN."
  exit 1
fi

if [ "$DOMAIN_IP" == "$SERVER_IP" ]; then
  echo "DNS entry found for the domain $DOMAIN pointing to the server's public IP address ($SERVER_IP)."
else
  echo "Error: The DNS entry for $DOMAIN does not point to the server's public IP address ($SERVER_IP)."
  exit 1
fi

read -p "Where should the redirection go? (e.g., 192.168.10.10:8080): " HOST

CONFIG_FILE="/etc/nginx/sites-available/$DOMAIN"
LINK_FILE="/etc/nginx/sites-enabled/$DOMAIN"

cat <<EOF >$CONFIG_FILE
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://$HOST;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

ln -s $CONFIG_FILE $LINK_FILE

nginx -t
if [ $? -eq 0 ]; then
  systemctl reload nginx
else
  echo "Error in Nginx configuration. Please check the file $CONFIG_FILE."
  exit 1
fi

# SSL
certbot --nginx -d $DOMAIN --non-interactive --agree-tos --email admin@$DOMAIN
if [ $? -ne 0 ]; then
  echo "Error generating the SSL certificate with Certbot."
  exit 1
fi

echo "The configuration for $DOMAIN has been successfully added, HTTPS is enabled, and an SSL certificate has been generated."
